server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6m9no05e4fiv3e1io.mysql.rds.aliyuncs.com:3306/eshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: circleliu
    password: Lyx19980320
  resources:
    static-locations: classpath:/templates,classpath:/static
mybatis:
  configuration:
    map-underscore-to-camel-case: true
